### PR TITLE
Add agent delete functionality

### PR DESCRIPTION
**Pull request by iluxame**

### CODE REVIEW

**Comment by iluxame** [comment]
Hi,

I can see that legacy api tests are broken but it seems to be not related to my commit.

**Comment by aconrad** [comment]
You are right, it's unrelated to your commit. I'll take a look today and figure out what's wrong. I want tests to pass before merging.

**Comment by aconrad** [comment]
The couverture-io report says the coverage has worsened. If you click "Details" you can see what's left to be tested, you are missing a use-case.

**Comment by iluxame** [comment]
Thanks for your review. I've added the relevant test case and now agent.py coverage is 100% again

**Comment by aconrad** [comment]
@msabramo mind reviewing this quickly?

**Comment by aconrad** [comment]
@iluxame can you please update the CHANGES file as well?

**Comment by iluxame** [comment]
@aconrad @msabramo Can you please review my pull request?

**Comment by aconrad** [comment]
@iluxame thanks for your contribution. I am going to merge this because the code looks good. Although I don't have the authority to make a release, I think only @msabramo has.

**Comment by msabramo** [comment]
Thanks, @aconrad for reviewing and fixing the build problems!

I'll draft a release...

**Pull request merged**
