### PR TITLE
Assorted fixes and features

### PR DESCRIPTION
**Pull request by gvalkov**
Hello @msabramo,

Nice work on the future API. It is shaping up great :+1: 

Here's a somewhat random collection of fixes and feature implementations. Please let me know if you're interested in any of them and if you'll need them packaged as separate PRs. I hope to be able to contribute more, but time for open-source projects has been scarce lately :(

Kind regards,
Georgi

### CODE REVIEW

**Comment by gvalkov** [comment]
Just saw the CI results - I'll fix the coverage and 2.6 compatibility issues later today.

**Comment by gvalkov** [comment]
Everything is green except the flake8 checks. Before fixing those, would you consider raising the max line width? The 80 characters suggested by pep8 is a bit behind the times, imho. For my projects, I've found that 100-120 is much more comfortable. Just a though.

**Comment by msabramo** [comment]
Thank you, @gvalkov!

**Comment by msabramo** [comment]
@gvalkov I decided to take your advice and increase the max line length to 120 in #79. Thanks again!

**Pull request merged**
