### PR TITLE
.travis.yml: Post coverage to couverture.io

### PR DESCRIPTION
**Pull request by msabramo**

### CODE REVIEW

**Comment by aconrad** [comment]
Hum... I guess code coverage cannot run for flake8. How can we conditionally run the curl command for specific builds?

**Comment by aconrad** [comment]
Very cool to see all these coverage reports, 👍 

Thanks for wiring it up @msabramo !

**Comment by aconrad** [comment]
👍

**Comment by msabramo** [comment]
@aconrad: I made it skip `flake8` builds by doing this: 729222a

**Pull request merged**
